name: Python package

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.12']
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  sudo apt -y install libgeos-dev
                  python -m pip install --upgrade pip setuptools wheel
                  pip install tox
            - name: Run tox
              run: |
                  tox -e flake8,${{ matrix.python-version }},${{ matrix.python-version }}-extra
